### ISSUE TITLE
Freezes on world load

### ISSUE THREAD

**Issue by azaquaz** [Lyinginbedmon/VariousOddities#10]
Using forge-36.1.18, varodd-1.16_001n, the game hangs forever on world load or world creation, generating this crash report:
https://pastebin.com/jDRhM5Pq
And putting this in the log:
https://pastebin.com/Amyq0y0M

**Comment by Lyinginbedmon** [comment]
Interestingly, the line of code responsible hasn't changed in many versions and this bug hasn't been reported or encountered in testing. I'll chuck a check in just to be safe and it'll be resolved next version.
