### ISSUE TITLE
Some status effects unobtainable & do nothing

### ISSUE THREAD

**Issue by JonJonsonsSon** [Lyinginbedmon/VariousOddities#2]
Neither commands like
/give @p potion 1 0 {Potion:"varodd:swim_boost"}
nor specifying new potion recipes using CraftTweaker (the result is pink, uncraftable potions) allow players to obtain swim boost pots.

Also, using:
/give @p potion 1 0 {Potion:"minecraft:water",CustomPotionEffects: [{Id:99,Duration:2147483647}],display:{Name:"Test Pot"}}
to generate a swim boost pot reveals that even if you use one, it won't have any effect. The game will *say* you're under the effects of a swim boost pot, but when you enter water and move around, unfortunately nothing happens.

**Comment by Lyinginbedmon** [comment]
Which version are you citing? I can categorically confirm that all the status effects work through the /effect command in the most recent versions. Otherwise they are almost exclusively obtained from in-mod items and effects.

**Comment by JonJonsonsSon** [comment]
varodd-1.12.2-4.07. I just created a new world and performed the same tests, and creating potions with the ID of the swim boost effect (99), then drinking them, has no effect other than showing the swim boost icon & countdown timer for the potion effect when players open their inventory.

Is there any chance that you'll add potions which grant the new effects that are added by your mod? That'd be really cool!

Edit: I just confirmed that obtaining the swim boost effect by equipping a ring of swimming also has no effect on movement speed in water.

**Comment by Lyinginbedmon** [comment]
Aha, something I can test for! Seems to be a problem with how the Entity.isInsideOfMaterial(Material) method operates, resulting in the potion not actually realising you're in water. I've written a different test for it that's closer to how being in lava is determined and that seems to properly function now.

Quite why testing these two things are completely and drastically-different operations in vanilla, I have no idea.

Next version!
