### ISSUE TITLE
Crash while right clicking a whole bunch with the coin purse

### ISSUE THREAD

**Issue by inkdear** [Lyinginbedmon/VariousOddities#4]
Log and crash report:
[latest.log](https://github.com/Lyinginbedmon/VariousOddities/files/3619045/latest.log)
[crash-2019-09-17_14.57.08-client.txt](https://github.com/Lyinginbedmon/VariousOddities/files/3619047/crash-2019-09-17_14.57.08-client.txt)

**Comment by Lyinginbedmon** [comment]
Looks to be an issue with the NBT data retrieval after the coin purse is emptied. An easy fix for next version, but for the time being just avoid right-clicking empty coin purses.
