### ISSUE TITLE
Internal Server Error with thaumcraft

### ISSUE THREAD

**Issue by Riernar** [Lyinginbedmon/VariousOddities#6]
Hi,
It seems the phylactery system is interacting with thaumcraft and producing `internal server error` when trying to connect to my server.
This server is in survival, so I can't see how anyone could have used the phylactery system.
I have kept `latest.log` and `debug.log` from both server and client, I can provide more log if necessary.
The server runs a customized pack, so there might be some interaction with other mods - some are mentioned in the error stack.

Thank you for your help !

### Error server-side:
https://pastebin.com/zrfn8ZwM

### error client-side:
No info in the log

### Versions:
forge-14.23.5.2847
varodd-1.12.2-5.2
thaumcraft-1.12.2-6.1.BETA26

**Comment by Riernar** [comment]
Additional info, if this helps: disabling the phylactery module allows to log back in the world. I'll keep the config like that since I don't need the phylactery system.
I'll still keep the files in case you want to look into that :)

**Comment by Lyinginbedmon** [comment]
The phylactery system is asking a Thaumcraft tile if it is empty, a vanilla function that Thaumcraft should have implemented. This isn't a problem with Various Oddities.
